modLoader="javafml"
loaderVersion="${fmlVersionRange}"
issueTrackerURL="https://github.com/christopherwalkerml/MoBees/issues"

license="GNU GPLv3"

[[mods]]
modId="mobees"
version="${version}"
displayName="Mo' Bees"
credits="binnie, thedarkcolour"
authors="Chris Walker (noodlepfp), Zeitheron (Zeith)"
description='''
	More Bees for Forestry CE Mod, backported to 1.19.2 alongside new content from Forestry CE 1.20.1
	'''

[[dependencies.mobees]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.mobees]]
modId="patchouli"
mandatory=true
versionRange="${patchouliVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.mobees]]
modId="forestry"
mandatory=true
versionRange="${forestryVersionRange}"
ordering="NONE"
side="CLIENT"

[[dependencies.mobees]]
modId="jei"
mandatory=false
versionRange="${jeiVersionRange}"
ordering="NONE"
side="CLIENT"
